### ISSUE TITLE
Feature request: Syncing (importing) of existing seeds

### ISSUE THREAD

**Issue by PatriQ94** [iotaledger/iota.go#114] opened 2019-07-09 08:09 UTC
### Description
Account Module (shortly _AM_) is a great addition to the IOTA stack, but for further adoption I think there's a crucial feature missing. That is, the creation of "new" Accounts with existing/old/previously used seeds. 

### Motivation
With the usage of the AM being recommended due to its statefullness over the manual implementation of seed management and standard lib usage, it is crucial to cover both freshly created seeds and already used seeds. One AM per device is understandable as it would be impossible to synchronize the same AM over multiple devices, but a feature of importing already old seeds and creating a new Account on a single device should be doable, no? For example now and in near future, most companies, developers and people integrating IOTA into their system rely on standard libs to do the work fast and well, while all using own implementations of seed management, which could be not-safe or inefficient. By having a way of an easy transition from own implementation to a well vetted, optimized and open source official implementation of the AM offered by IF could have great impact on their processes and ease of use of the Tangle. That being said, I think there could be a way to implement a procedure/syncing method, that takes in an old seed, and starts syncing (much like Trinity by checking _n_ amount of addresses (or something similar)) and build up a local state of the Account, much like it is now. This could perhaps be even extended so the currently existing Accounts have a method of syncing. This could also allow the same Account to be on multiple devices as long as they never run simultaneously, but take turns running and sync their state beforehand. 

### Requirements
- Syncing method that takes in an old seed, generates an "new" local Account, syncs up and builds its state (much like Trinity)
- OPTIONAL (Syncing up/refreshing the state of any Account)

### Open Questions (optional)
- What would be the methods of syncing?
- If it were to check _n_ addresses like Trinity, how would the user interact with the lib in case there hasn't been enough addresses checked in the first iteration?

### Am I planning to do it myself with a PR?
No.

**Comment by luca-moser** [comment] 2019-07-09 08:43
Hey PatriQ
>it is crucial to cover both freshly created seeds and already used seeds. 

I fail to understand why it is important to have a transition functionality in the library, given that the amount of seeds which need to be transitioned is really low and there's no 100% deterministic way to do build up an account just from a seed. (which is one of the reasons why a new seed is required).

Given a person which has an old seed with 1Mi on it, scattered over 100 addresses: It is much easier if that person simply creates a new seed, initializes an account, creates a new CDA and then deposits all funds from his/her previous seed onto the account.

If an automatic transition function should do the job, it has no knowledge over the addresses which were generated with that seed. The addresses containing the funds could be scattered in any random spacing.

>This could also allow the same Account to be on multiple devices as long as they never run simultaneously, but take turns running and sync their state beforehand.

Synchronizing the account state over multiple devices using the same seed must be done by a higher-level coordination and is not recommended exactly because one must get the synchronization part right.

Overall, I currently do not see a good enough reason for adding such functionality as there is only a low amount of seeds which would need to be transitioned anyway.

I will leave this issue open but I won't invest time in implementing it in the foreseeable future.

---

Lets say we want to add such functionality, what kind of requirements must be met in order to be able to transition correctly?:
* There must not be any ongoing deposits/withdrawals from any address generated from the seed
* The user must know the last key index used for generating addresses

Given this two requirements, we can do following for transitioning:
1. Generate all addresses up to the last used key index
2. Gather all addresses with funds
3. Allocate a new CDA with `last used key index + 1` with the expected amount equal to the funds
4. Issue a deposit from all gathered addresses to the newly allocated CDA
5. Block the `Transition()` function as long as the deposit isn't confirmed.

This procedure ensures, that all addresses not allocated by the account module will not be further used/make part of the account's state.

**Comment by PatriQ94** [comment] 2019-07-09 09:38
> given that the amount of seeds which need to be transitioned is really low

How do we know this? Perhaps this is the truth cause we're still in early stages, so not many people are familiar with the AM since AM is one of the newest additions on the IOTA stack. I guess we'll see with time. 

> there's no 100% deterministic way to do build up an account just from a seed.

Yes, completely agree with this, no way to do it with just a seed. There would definitely have to be some restrictions and conditions upon which a transition would be doable, like the ones you've mentioned. 

> I will leave this issue open but I won't invest time in implementing it in the foreseeable future.

Understandable. We'll see with time if question/demand regarding this increases. This is also the reason why I wrote this here instead of Discord, so it's more visible and easier to find in case a question on this pops up again.

**Comment by luca-moser** [comment] 2020-06-16 16:51
Bigger changes will probably be part of the Rust core lib. Closing this issue since this won't be implemented probably in this lib.

**Closed by luca-moser** 2020-06-16 16:51 UTC
Labels: needs more input
